// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5oGNBuX3NooixlrOi_quC2w_8GgcSqKU',
    appId: '1:1043079191765:web:ad5c7a6a6adef7ea97165c',
    messagingSenderId: '1043079191765',
    projectId: 'parking-manager-11a88',
    authDomain: 'parking-manager-11a88.firebaseapp.com',
    storageBucket: 'parking-manager-11a88.firebasestorage.app',
    measurementId: 'G-VQMYZYLHPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRlD6KpJfye6Keo6eiDGQ3nzvAzOz1YU',
    appId: '1:1043079191765:android:1eddbd9986c27be997165c',
    messagingSenderId: '1043079191765',
    projectId: 'parking-manager-11a88',
    storageBucket: 'parking-manager-11a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6IFGZWadTLKiV9MniC4uenOa8JtXB0oo',
    appId: '1:1043079191765:ios:0485e40b9962a8de97165c',
    messagingSenderId: '1043079191765',
    projectId: 'parking-manager-11a88',
    storageBucket: 'parking-manager-11a88.firebasestorage.app',
    iosBundleId: 'com.example.parkingManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6IFGZWadTLKiV9MniC4uenOa8JtXB0oo',
    appId: '1:1043079191765:ios:0485e40b9962a8de97165c',
    messagingSenderId: '1043079191765',
    projectId: 'parking-manager-11a88',
    storageBucket: 'parking-manager-11a88.firebasestorage.app',
    iosBundleId: 'com.example.parkingManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5oGNBuX3NooixlrOi_quC2w_8GgcSqKU',
    appId: '1:1043079191765:web:ede639d16df4119797165c',
    messagingSenderId: '1043079191765',
    projectId: 'parking-manager-11a88',
    authDomain: 'parking-manager-11a88.firebaseapp.com',
    storageBucket: 'parking-manager-11a88.firebasestorage.app',
    measurementId: 'G-19VCFWQF6J',
  );
}
